import {useMemo,useState} from 'react'; import {addSchedule,completeSchedule,exportCSV,exportJSON,loadSchedules,saveSchedules,type Schedule} from './db';
const menu=['홈','일정','전체목록','가전','자동차','통신','보험','마루','집관리','증여','문서'];
const days=(d:string)=>Math.ceil((new Date(d+'T00:00:00').getTime()-new Date(new Date().toDateString()).getTime())/86400000);
function dl(name:string,text:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();}
export default function App(){const [tab,setTab]=useState('홈');const [rows,setRows]=useState<Schedule[]>(loadSchedules());const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [date,setDate]=useState('');
const active=rows.filter(x=>!x.completed).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const groups=useMemo(()=>({today:active.filter(x=>days(x.dueDate)<=0),week:active.filter(x=>days(x.dueDate)>0&&days(x.dueDate)<=7),month:active.filter(x=>days(x.dueDate)>7&&days(x.dueDate)<=31)}),[active]);
const refresh=()=>setRows(loadSchedules());const add=()=>{if(!title||!date)return;addSchedule(title,date,2);setTitle('');setDate('');setOpen(false);refresh()};
return <div className="app"><aside><h1>우리집<br/>통합관리</h1>{menu.map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button className="quick" onClick={()=>setOpen(true)}>＋ 빠른 등록</button></aside><main><header><div><small>우리집 통합관리</small><h2>{tab}</h2></div><div><button onClick={()=>dl('우리집_통합관리.json',exportJSON(),'application/json')}>JSON</button><button onClick={()=>dl('일정.csv',exportCSV(),'text/csv;charset=utf-8')}>CSV</button><button className="dark" onClick={()=>setOpen(true)}>＋ 등록</button></div></header>{tab==='홈'?<Home groups={groups} done={(id)=>{completeSchedule(id);refresh()}}/>:tab==='일정'?<List rows={active} done={(id)=>{completeSchedule(id);refresh()}}/>:<div className="placeholder"><b>{tab}</b><p>공통 데이터 구조에 연결될 카테고리 화면입니다.</p></div>}{open&&<div className="back" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h3>일정 등록</h3><label>할 일<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 자동차보험 갱신"/></label><label>날짜<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="actions"><button onClick={()=>setOpen(false)}>취소</button><button className="dark" onClick={add}>저장</button></div></div></div>}</main></div>}
function Home({groups,done}:{groups:any,done:(id:number)=>void}){return <><div className="stats"><Stat t="오늘 해야 할 일" n={groups.today.length}/><Stat t="7일 이내" n={groups.week.length}/><Stat t="30일 이내" n={groups.month.length}/></div><h3 className="sect">다가오는 일정</h3><div className="cards">{[...groups.today,...groups.week,...groups.month].slice(0,12).map((x:Schedule)=><Card x={x} done={done} />)}</div></>}
function Stat({t,n}:{t:string,n:number}){return <div className="stat"><small>{t}</small><strong>{n}</strong><span>건</span></div>}
function Card({x,done}:{x:Schedule,done:(id:number)=>void}){const d=days(x.dueDate);return <article><div className="top"><b>{d<=0?'오늘':`D-${d}`}</b><button onClick={()=>done(x.id)}>완료</button></div><h3>{x.title}</h3><p>{x.category} · {x.dueDate}</p></article>}
function List({rows,done}:{rows:Schedule[],done:(id:number)=>void}){return <><div className="sectrow"><h3>전체 일정</h3><span>{rows.length}건</span></div><div className="cards">{rows.map(x=><Card key={x.id} x={x} done={done}/>)}</div></>}
