import initSqlJs,{type Database} from "sql.js";
export type Schedule={id:number;title:string;due_date:string;priority:number;category:string;item_name:string;completed:number;created_at:string};
const KEY="our-home-management.sqlite"; let db:Database|null=null;
async function persist(){if(!db)return;const b=db.export();localStorage.setItem(KEY,btoa(String.fromCharCode(...b)));}
export async function initDB(){const SQL=await initSqlJs({locateFile:f=>new URL(`sql-wasm.wasm`,import.meta.url).toString()});const s=localStorage.getItem(KEY);db=s?new SQL.Database(Uint8Array.from(atob(s),c=>c.charCodeAt(0))):new SQL.Database();db.run(`CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT,category TEXT NOT NULL,name TEXT NOT NULL,manufacturer TEXT DEFAULT '',model TEXT DEFAULT '',purchase_date TEXT DEFAULT '',purchase_price INTEGER DEFAULT 0,memo TEXT DEFAULT '',created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS schedules(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,due_date TEXT NOT NULL,priority INTEGER NOT NULL DEFAULT 2,category TEXT NOT NULL DEFAULT '일정',item_name TEXT NOT NULL DEFAULT '',completed INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER,name TEXT NOT NULL,mime_type TEXT NOT NULL,blob_data BLOB NOT NULL,created_at TEXT NOT NULL);`);await persist();}
function D(){if(!db)throw Error("DB not ready");return db}
export function querySchedules():Schedule[]{const r=D().exec(`SELECT id,title,due_date,priority,category,item_name,completed,created_at FROM schedules WHERE completed=0 ORDER BY due_date,priority,id`);return r.length?r[0].values.map(x=>({id:+x[0]!,title:String(x[1]),due_date:String(x[2]),priority:+x[3]!,category:String(x[4]),item_name:String(x[5]),completed:+x[6]!,created_at:String(x[7])})):[]}
export function addSchedule(title:string,date:string,priority=2){D().run(`INSERT INTO schedules(title,due_date,priority,created_at) VALUES(?,?,?,?)`,[title,date,priority,new Date().toISOString()]);void persist()}
export function completeSchedule(id:number){D().run(`UPDATE schedules SET completed=1 WHERE id=?`,[id]);void persist()}
export function getItemCounts(){const r=D().exec(`SELECT category,COUNT(*) FROM items GROUP BY category`);const o:Record<string,number>={};if(r.length)for(const x of r[0].values)o[String(x[0])]=+x[1]!;return o}
export function exportJson(){const out:any={app:"우리집 통합관리",schema_version:1,exported_at:new Date().toISOString(),data:{}};for(const t of ["items","schedules","documents"]){const r=D().exec(`SELECT * FROM ${t}`);out.data[t]=r.length?r[0].values.map(row=>Object.fromEntries(r[0].columns.map((c,i)=>[c,row[i]]))):[]}return JSON.stringify(out,null,2)}
export function exportCsvSchedules(){const q=querySchedules();return "\uFEFFid,title,due_date,priority,category,item_name,completed,created_at\n"+q.map(x=>[x.id,`"${x.title.replaceAll('"','""')}"`,x.due_date,x.priority,`"${x.category}"`,`"${x.item_name}"`,x.completed,x.created_at].join(",")).join("\n")}
